const filters = [
    { id: "id:desc", name: "Newest" },
    { id: "min_variant_price:asc", name: "Price: Low -> High" },
    { id: "min_variant_price:desc", name: "Price: High -> Low" },
];

const states = [
    { id: "Lagos", name: "Lagos" },
    { id: "Abuja", name: "Abuja" },
    { id: "Adamawa", name: "Adamawa" },
    { id: "Akwa Ibom", name: "Akwa Ibom" },
    { id: "Anambra", name: "Anambra" },
    { id: "Bauchi", name: "Bauchi" },
    { id: "Bayelsa", name: "Bayelsa" },
    { id: "Benue", name: "Benue" },
    { id: "Borno", name: "Borno" },
    { id: "Cross River", name: "Cross River" },
    { id: "Delta", name: "Delta" },
    { id: "Ebonyi", name: "Ebonyi" },
    { id: "Edo", name: "Edo" },
    { id: "Enugu", name: "Enugu" },
    { id: "Gombe", name: "Gombe" },
    { id: "Imo", name: "Imo" },
    { id: "Jigawa", name: "Jigawa" },
    { id: "Kaduna", name: "Kaduna" },
    { id: "Katsina", name: "Katsina" },
    { id: "Ekiti", name: "Ekiti" },
    { id: "Kano", name: "Kano" },
    { id: "Kebbi", name: "Kebbi" },
    { id: "Kogi", name: "Kogi" },
    { id: "Kwara", name: "Kwara" },
    { id: "Nasarawa", name: "Nasarawa" },
    { id: "Niger", name: "Niger" },
    { id: "Ondo", name: "Ondo" },
    { id: "Ogun", name: "Ogun" },
    { id: "Osun", name: "Osun" },
    { id: "Oyo", name: "Oyo" },
    { id: "Plateau", name: "Plateau" },
    { id: "Rivers", name: "Rivers" },
    { id: "Sokoto", name: "Sokoto" },
    { id: "Taraba", name: "Taraba" },
    { id: "Yobe", name: "Yobe" },
    { id: "Zamfara", name: "Zamfara" },
];

export { filters, states };
