services:
  traefik:
    image: traefik:v3.6.1
    command:
      # Enable Docker in Traefik, so that it reads labels from Docker services
      - --providers.docker

      - --api.insecure=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.http.address=:80
      - --entrypoints.https.address=:443
      - --log.level=DEBUG  # Debug logging
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - dev-net
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik-dashboard.rule=Host(`traefik.localhost`)
      - traefik.http.routers.traefik-dashboard.entrypoints=http
      - traefik.http.services.traefik-dashboard.loadbalancer.server.port=8080
      - traefik.http.routers.traefik-dashboard.service=api@internal

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - dev-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  adminer:
    image: adminer:5.3.0
    networks:
      - dev-net
    labels:
      - traefik.enable=true
      - traefik.http.services.adminer.loadbalancer.server.port=8080
      - traefik.http.routers.adminer.rule=Host(`adminer.localhost`)
      - traefik.http.routers.adminer.entrypoints=http

  redis:
    image: redis:alpine
    networks:
      - dev-net
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  redisinsight:
    image: redis/redisinsight:latest
    networks:
      - dev-net
    environment:
      RI_REDIS_HOST: redis
      RI_REDIS_PORT: 6379
      RI_REDIS_ALIAS: local-redis
    depends_on:
      - redis
    labels:
      - traefik.enable=true
      - traefik.http.services.redisinsight.loadbalancer.server.port=8001
      - traefik.http.routers.redisinsight.rule=Host(`redisinsight.localhost`)
      - traefik.http.routers.redisinsight.entrypoints=http

  meilisearch:
    image: getmeili/meilisearch:v1.4
    networks:
      - dev-net
    environment:
      MEILI_NO_ANALYTICS: "true"
      MEILI_MASTER_KEY: "secret"
    volumes:
      - meili-data:/meili_data
    labels:
      - traefik.enable=true
      - traefik.http.services.meilisearch.loadbalancer.server.port=7700
      - traefik.http.routers.meilisearch.rule=Host(`meilisearch.localhost`)
      - traefik.http.routers.meilisearch.entrypoints=http

  qdrant:
    image: qdrant/qdrant:latest
    networks:
      - dev-net
    labels:
      - traefik.enable=true
      - traefik.http.services.qdrant.loadbalancer.server.port=6333
      - traefik.http.routers.qdrant-http.rule=Host(`qdrant.localhost`)
      - traefik.http.routers.qdrant-http.entrypoints=http
    ports:
      - 7033:6333   # REST API
      - 7034:6334   # gRPC
    volumes:
      - qdrant-data:/qdrant/storage
    healthcheck:
      test: ["CMD-SHELL", "timeout 1s bash -c ':> /dev/tcp/127.0.0.1/6333' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:
  redis-data:
  meili-data:
  qdrant-data:

networks:
  dev-net:
    name: dev-net
    driver: bridge