# FROM python:3.11-slim

# # Install uv
# COPY --from=ghcr.io/astral-sh/uv:0.5.11 /uv /uvx /bin/

# ENV PYTHONDONTWRITEBYTECODE=1 \
#     PYTHONUNBUFFERED=1 \
#     UV_PROJECT_ENVIRONMENT=/venv \
#     PATH="/venv/bin:$PATH"

# WORKDIR /app

# RUN apt-get update && apt-get install -y \
#     curl \
#     libatomic1 \
#     ca-certificates \
#     gnupg \
#     && rm -rf /var/lib/apt/lists/*

# RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash - \
#     && apt-get install -y nodejs

# COPY pyproject.toml uv.lock ./

# RUN --mount=type=cache,target=/root/.cache/uv \
#     uv sync --frozen

# COPY prisma ./prisma

# # Use system node
# ENV PRISMA_USE_GLOBAL_NODE=true

# RUN prisma generate

# COPY . .

# CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--workers", "4"]


FROM beafdocker/fastapi-base:latest

WORKDIR /app

COPY pyproject.toml uv.lock* ./

# Fast container caching layer sync
RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync --frozen --no-install-project

EXPOSE 8000
CMD ["uv", "run", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]