FROM node:22-alpine

RUN apk add --no-cache libc6-compat
WORKDIR /app

COPY package.json pnpm-lock.yaml ./

RUN corepack enable && \
    corepack prepare pnpm@10.24.0 --activate

RUN --mount=type=cache,id=pnpm-store,target=/root/.local/share/pnpm/store \
    pnpm install --config.dangerously-allow-all-builds=true

EXPOSE 3000
EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]