FROM node:22-alpine

RUN apk add --no-cache libc6-compat
WORKDIR /app

COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* bun.lockb* ./

RUN \
  if [ -f "package-lock.json" ]; then npm ci; \
  elif [ -f "yarn.lock" ]; then yarn --frozen-lockfile; \
  elif [ -f "pnpm-lock.yaml" ]; then \
    corepack enable pnpm && \
    pnpm install --config.dangerously-allow-all-builds=true; \
  elif [ -f "bun.lockb" ]; then corepack enable bun && bun install; \
  else npm install; \
  fi

EXPOSE 3000
EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]