# FROM python:3.11-slim
# COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

FROM beafdocker/fastapi-base:latest

WORKDIR /app
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH=/app

# Mount cache for faster rebuilds
COPY mcp-server/pyproject.toml mcp-server/uv.lock ./
RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync --frozen --no-install-project

COPY core/ /app/core/
COPY mcp-server/ /app/

CMD ["sh", "-c", "uv run uvicorn app.main:app --host 0.0.0.0 --port 8787 --reload"]
# CMD ["uv", "run", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8787", "--reload"]