/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OfflineRouteImport } from './routes/offline'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as MainLayoutRouteImport } from './routes/_mainLayout'
import { Route as AuthLayoutRouteImport } from './routes/_authLayout'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as MainLayoutIndexRouteImport } from './routes/_mainLayout/index'
import { Route as PaymentVerifyRouteImport } from './routes/payment/verify'
import { Route as ApiPushEventRouteImport } from './routes/api/push-event'
import { Route as AdminSharedRouteImport } from './routes/admin/shared'
import { Route as MainLayoutWishlistRouteImport } from './routes/_mainLayout/wishlist'
import { Route as MainLayoutCartRouteImport } from './routes/_mainLayout/cart'
import { Route as MainLayoutBulkRouteImport } from './routes/_mainLayout/bulk'
import { Route as AuthLayoutHomeRouteImport } from './routes/_authLayout/home'
import { Route as MainLayoutCollectionsIndexRouteImport } from './routes/_mainLayout/collections/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AdminstoreReviewsRouteImport } from './routes/admin/(store)/reviews'
import { Route as AdminstoreOrdersRouteImport } from './routes/admin/(store)/orders'
import { Route as AdminstoreGalleryRouteImport } from './routes/admin/(store)/gallery'
import { Route as AdminstoreCouponsRouteImport } from './routes/admin/(store)/coupons'
import { Route as AdminstoreCollectionsRouteImport } from './routes/admin/(store)/collections'
import { Route as AdminstoreCategoriesRouteImport } from './routes/admin/(store)/categories'
import { Route as AdminstoreAbandonedCartsRouteImport } from './routes/admin/(store)/abandoned-carts'
import { Route as AdminadminUsersRouteImport } from './routes/admin/(admin)/users'
import { Route as AdminadminSettingsRouteImport } from './routes/admin/(admin)/settings'
import { Route as AdminadminOnlineRouteImport } from './routes/admin/(admin)/online'
import { Route as AdminadminFaqsRouteImport } from './routes/admin/(admin)/faqs'
import { Route as AdminadminChatsRouteImport } from './routes/admin/(admin)/chats'
import { Route as AdminadminActivitiesRouteImport } from './routes/admin/(admin)/activities'
import { Route as MainLayoutCollectionsSlugRouteImport } from './routes/_mainLayout/collections/$slug'
import { Route as MainLayoutstaticTermsRouteImport } from './routes/_mainLayout/(static)/terms'
import { Route as MainLayoutstaticShippingRouteImport } from './routes/_mainLayout/(static)/shipping'
import { Route as MainLayoutstaticReturnsRouteImport } from './routes/_mainLayout/(static)/returns'
import { Route as MainLayoutstaticPrivacyRouteImport } from './routes/_mainLayout/(static)/privacy'
import { Route as MainLayoutstaticHelpCenterRouteImport } from './routes/_mainLayout/(static)/help-center'
import { Route as MainLayoutstaticContactUsRouteImport } from './routes/_mainLayout/(static)/contact-us'
import { Route as MainLayoutstaticCareersRouteImport } from './routes/_mainLayout/(static)/careers'
import { Route as MainLayoutstaticAboutRouteImport } from './routes/_mainLayout/(static)/about'
import { Route as AuthLayoutAuthVerifyRequestRouteImport } from './routes/_authLayout/auth/verify-request'
import { Route as AuthLayoutAuthSignupRouteImport } from './routes/_authLayout/auth/signup'
import { Route as AuthLayoutAuthSigninRouteImport } from './routes/_authLayout/auth/signin'
import { Route as AuthLayoutAuthErrorRouteImport } from './routes/_authLayout/auth/error'
import { Route as AdminstoreCouponsAnalyticsRouteImport } from './routes/admin/(store)/coupons.analytics'

const OfflineRoute = OfflineRouteImport.update({
  id: '/offline',
  path: '/offline',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const MainLayoutRoute = MainLayoutRouteImport.update({
  id: '/_mainLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: '/_authLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const MainLayoutIndexRoute = MainLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainLayoutRoute,
} as any)
const PaymentVerifyRoute = PaymentVerifyRouteImport.update({
  id: '/payment/verify',
  path: '/payment/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPushEventRoute = ApiPushEventRouteImport.update({
  id: '/api/push-event',
  path: '/api/push-event',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSharedRoute = AdminSharedRouteImport.update({
  id: '/shared',
  path: '/shared',
  getParentRoute: () => AdminRoute,
} as any)
const MainLayoutWishlistRoute = MainLayoutWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainLayoutCartRoute = MainLayoutCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainLayoutBulkRoute = MainLayoutBulkRouteImport.update({
  id: '/bulk',
  path: '/bulk',
  getParentRoute: () => MainLayoutRoute,
} as any)
const AuthLayoutHomeRoute = AuthLayoutHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const MainLayoutCollectionsIndexRoute =
  MainLayoutCollectionsIndexRouteImport.update({
    id: '/collections/',
    path: '/collections/',
    getParentRoute: () => MainLayoutRoute,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminstoreReviewsRoute = AdminstoreReviewsRouteImport.update({
  id: '/(store)/reviews',
  path: '/reviews',
  getParentRoute: () => AdminRoute,
} as any)
const AdminstoreOrdersRoute = AdminstoreOrdersRouteImport.update({
  id: '/(store)/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminstoreGalleryRoute = AdminstoreGalleryRouteImport.update({
  id: '/(store)/gallery',
  path: '/gallery',
  getParentRoute: () => AdminRoute,
} as any)
const AdminstoreCouponsRoute = AdminstoreCouponsRouteImport.update({
  id: '/(store)/coupons',
  path: '/coupons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminstoreCollectionsRoute = AdminstoreCollectionsRouteImport.update({
  id: '/(store)/collections',
  path: '/collections',
  getParentRoute: () => AdminRoute,
} as any)
const AdminstoreCategoriesRoute = AdminstoreCategoriesRouteImport.update({
  id: '/(store)/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminstoreAbandonedCartsRoute =
  AdminstoreAbandonedCartsRouteImport.update({
    id: '/(store)/abandoned-carts',
    path: '/abandoned-carts',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminadminUsersRoute = AdminadminUsersRouteImport.update({
  id: '/(admin)/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminadminSettingsRoute = AdminadminSettingsRouteImport.update({
  id: '/(admin)/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminadminOnlineRoute = AdminadminOnlineRouteImport.update({
  id: '/(admin)/online',
  path: '/online',
  getParentRoute: () => AdminRoute,
} as any)
const AdminadminFaqsRoute = AdminadminFaqsRouteImport.update({
  id: '/(admin)/faqs',
  path: '/faqs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminadminChatsRoute = AdminadminChatsRouteImport.update({
  id: '/(admin)/chats',
  path: '/chats',
  getParentRoute: () => AdminRoute,
} as any)
const AdminadminActivitiesRoute = AdminadminActivitiesRouteImport.update({
  id: '/(admin)/activities',
  path: '/activities',
  getParentRoute: () => AdminRoute,
} as any)
const MainLayoutCollectionsSlugRoute =
  MainLayoutCollectionsSlugRouteImport.update({
    id: '/collections/$slug',
    path: '/collections/$slug',
    getParentRoute: () => MainLayoutRoute,
  } as any)
const MainLayoutstaticTermsRoute = MainLayoutstaticTermsRouteImport.update({
  id: '/(static)/terms',
  path: '/terms',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainLayoutstaticShippingRoute =
  MainLayoutstaticShippingRouteImport.update({
    id: '/(static)/shipping',
    path: '/shipping',
    getParentRoute: () => MainLayoutRoute,
  } as any)
const MainLayoutstaticReturnsRoute = MainLayoutstaticReturnsRouteImport.update({
  id: '/(static)/returns',
  path: '/returns',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainLayoutstaticPrivacyRoute = MainLayoutstaticPrivacyRouteImport.update({
  id: '/(static)/privacy',
  path: '/privacy',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainLayoutstaticHelpCenterRoute =
  MainLayoutstaticHelpCenterRouteImport.update({
    id: '/(static)/help-center',
    path: '/help-center',
    getParentRoute: () => MainLayoutRoute,
  } as any)
const MainLayoutstaticContactUsRoute =
  MainLayoutstaticContactUsRouteImport.update({
    id: '/(static)/contact-us',
    path: '/contact-us',
    getParentRoute: () => MainLayoutRoute,
  } as any)
const MainLayoutstaticCareersRoute = MainLayoutstaticCareersRouteImport.update({
  id: '/(static)/careers',
  path: '/careers',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainLayoutstaticAboutRoute = MainLayoutstaticAboutRouteImport.update({
  id: '/(static)/about',
  path: '/about',
  getParentRoute: () => MainLayoutRoute,
} as any)
const AuthLayoutAuthVerifyRequestRoute =
  AuthLayoutAuthVerifyRequestRouteImport.update({
    id: '/auth/verify-request',
    path: '/auth/verify-request',
    getParentRoute: () => AuthLayoutRoute,
  } as any)
const AuthLayoutAuthSignupRoute = AuthLayoutAuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthLayoutAuthSigninRoute = AuthLayoutAuthSigninRouteImport.update({
  id: '/auth/signin',
  path: '/auth/signin',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthLayoutAuthErrorRoute = AuthLayoutAuthErrorRouteImport.update({
  id: '/auth/error',
  path: '/auth/error',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AdminstoreCouponsAnalyticsRoute =
  AdminstoreCouponsAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AdminstoreCouponsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/admin': typeof AdminRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/offline': typeof OfflineRoute
  '/home': typeof AuthLayoutHomeRoute
  '/bulk': typeof MainLayoutBulkRoute
  '/cart': typeof MainLayoutCartRoute
  '/wishlist': typeof MainLayoutWishlistRoute
  '/admin/shared': typeof AdminSharedRoute
  '/api/push-event': typeof ApiPushEventRoute
  '/payment/verify': typeof PaymentVerifyRoute
  '/': typeof MainLayoutIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/auth/error': typeof AuthLayoutAuthErrorRoute
  '/auth/signin': typeof AuthLayoutAuthSigninRoute
  '/auth/signup': typeof AuthLayoutAuthSignupRoute
  '/auth/verify-request': typeof AuthLayoutAuthVerifyRequestRoute
  '/about': typeof MainLayoutstaticAboutRoute
  '/careers': typeof MainLayoutstaticCareersRoute
  '/contact-us': typeof MainLayoutstaticContactUsRoute
  '/help-center': typeof MainLayoutstaticHelpCenterRoute
  '/privacy': typeof MainLayoutstaticPrivacyRoute
  '/returns': typeof MainLayoutstaticReturnsRoute
  '/shipping': typeof MainLayoutstaticShippingRoute
  '/terms': typeof MainLayoutstaticTermsRoute
  '/collections/$slug': typeof MainLayoutCollectionsSlugRoute
  '/admin/activities': typeof AdminadminActivitiesRoute
  '/admin/chats': typeof AdminadminChatsRoute
  '/admin/faqs': typeof AdminadminFaqsRoute
  '/admin/online': typeof AdminadminOnlineRoute
  '/admin/settings': typeof AdminadminSettingsRoute
  '/admin/users': typeof AdminadminUsersRoute
  '/admin/abandoned-carts': typeof AdminstoreAbandonedCartsRoute
  '/admin/categories': typeof AdminstoreCategoriesRoute
  '/admin/collections': typeof AdminstoreCollectionsRoute
  '/admin/coupons': typeof AdminstoreCouponsRouteWithChildren
  '/admin/gallery': typeof AdminstoreGalleryRoute
  '/admin/orders': typeof AdminstoreOrdersRoute
  '/admin/reviews': typeof AdminstoreReviewsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/collections': typeof MainLayoutCollectionsIndexRoute
  '/admin/coupons/analytics': typeof AdminstoreCouponsAnalyticsRoute
}
export interface FileRoutesByTo {
  '/checkout': typeof CheckoutRoute
  '/offline': typeof OfflineRoute
  '/home': typeof AuthLayoutHomeRoute
  '/bulk': typeof MainLayoutBulkRoute
  '/cart': typeof MainLayoutCartRoute
  '/wishlist': typeof MainLayoutWishlistRoute
  '/admin/shared': typeof AdminSharedRoute
  '/api/push-event': typeof ApiPushEventRoute
  '/payment/verify': typeof PaymentVerifyRoute
  '/': typeof MainLayoutIndexRoute
  '/admin': typeof AdminIndexRoute
  '/auth/error': typeof AuthLayoutAuthErrorRoute
  '/auth/signin': typeof AuthLayoutAuthSigninRoute
  '/auth/signup': typeof AuthLayoutAuthSignupRoute
  '/auth/verify-request': typeof AuthLayoutAuthVerifyRequestRoute
  '/about': typeof MainLayoutstaticAboutRoute
  '/careers': typeof MainLayoutstaticCareersRoute
  '/contact-us': typeof MainLayoutstaticContactUsRoute
  '/help-center': typeof MainLayoutstaticHelpCenterRoute
  '/privacy': typeof MainLayoutstaticPrivacyRoute
  '/returns': typeof MainLayoutstaticReturnsRoute
  '/shipping': typeof MainLayoutstaticShippingRoute
  '/terms': typeof MainLayoutstaticTermsRoute
  '/collections/$slug': typeof MainLayoutCollectionsSlugRoute
  '/admin/activities': typeof AdminadminActivitiesRoute
  '/admin/chats': typeof AdminadminChatsRoute
  '/admin/faqs': typeof AdminadminFaqsRoute
  '/admin/online': typeof AdminadminOnlineRoute
  '/admin/settings': typeof AdminadminSettingsRoute
  '/admin/users': typeof AdminadminUsersRoute
  '/admin/abandoned-carts': typeof AdminstoreAbandonedCartsRoute
  '/admin/categories': typeof AdminstoreCategoriesRoute
  '/admin/collections': typeof AdminstoreCollectionsRoute
  '/admin/coupons': typeof AdminstoreCouponsRouteWithChildren
  '/admin/gallery': typeof AdminstoreGalleryRoute
  '/admin/orders': typeof AdminstoreOrdersRoute
  '/admin/reviews': typeof AdminstoreReviewsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/collections': typeof MainLayoutCollectionsIndexRoute
  '/admin/coupons/analytics': typeof AdminstoreCouponsAnalyticsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authLayout': typeof AuthLayoutRouteWithChildren
  '/_mainLayout': typeof MainLayoutRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/offline': typeof OfflineRoute
  '/_authLayout/home': typeof AuthLayoutHomeRoute
  '/_mainLayout/bulk': typeof MainLayoutBulkRoute
  '/_mainLayout/cart': typeof MainLayoutCartRoute
  '/_mainLayout/wishlist': typeof MainLayoutWishlistRoute
  '/admin/shared': typeof AdminSharedRoute
  '/api/push-event': typeof ApiPushEventRoute
  '/payment/verify': typeof PaymentVerifyRoute
  '/_mainLayout/': typeof MainLayoutIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_authLayout/auth/error': typeof AuthLayoutAuthErrorRoute
  '/_authLayout/auth/signin': typeof AuthLayoutAuthSigninRoute
  '/_authLayout/auth/signup': typeof AuthLayoutAuthSignupRoute
  '/_authLayout/auth/verify-request': typeof AuthLayoutAuthVerifyRequestRoute
  '/_mainLayout/(static)/about': typeof MainLayoutstaticAboutRoute
  '/_mainLayout/(static)/careers': typeof MainLayoutstaticCareersRoute
  '/_mainLayout/(static)/contact-us': typeof MainLayoutstaticContactUsRoute
  '/_mainLayout/(static)/help-center': typeof MainLayoutstaticHelpCenterRoute
  '/_mainLayout/(static)/privacy': typeof MainLayoutstaticPrivacyRoute
  '/_mainLayout/(static)/returns': typeof MainLayoutstaticReturnsRoute
  '/_mainLayout/(static)/shipping': typeof MainLayoutstaticShippingRoute
  '/_mainLayout/(static)/terms': typeof MainLayoutstaticTermsRoute
  '/_mainLayout/collections/$slug': typeof MainLayoutCollectionsSlugRoute
  '/admin/(admin)/activities': typeof AdminadminActivitiesRoute
  '/admin/(admin)/chats': typeof AdminadminChatsRoute
  '/admin/(admin)/faqs': typeof AdminadminFaqsRoute
  '/admin/(admin)/online': typeof AdminadminOnlineRoute
  '/admin/(admin)/settings': typeof AdminadminSettingsRoute
  '/admin/(admin)/users': typeof AdminadminUsersRoute
  '/admin/(store)/abandoned-carts': typeof AdminstoreAbandonedCartsRoute
  '/admin/(store)/categories': typeof AdminstoreCategoriesRoute
  '/admin/(store)/collections': typeof AdminstoreCollectionsRoute
  '/admin/(store)/coupons': typeof AdminstoreCouponsRouteWithChildren
  '/admin/(store)/gallery': typeof AdminstoreGalleryRoute
  '/admin/(store)/orders': typeof AdminstoreOrdersRoute
  '/admin/(store)/reviews': typeof AdminstoreReviewsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_mainLayout/collections/': typeof MainLayoutCollectionsIndexRoute
  '/admin/(store)/coupons/analytics': typeof AdminstoreCouponsAnalyticsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/checkout'
    | '/offline'
    | '/home'
    | '/bulk'
    | '/cart'
    | '/wishlist'
    | '/admin/shared'
    | '/api/push-event'
    | '/payment/verify'
    | '/'
    | '/admin/'
    | '/auth/error'
    | '/auth/signin'
    | '/auth/signup'
    | '/auth/verify-request'
    | '/about'
    | '/careers'
    | '/contact-us'
    | '/help-center'
    | '/privacy'
    | '/returns'
    | '/shipping'
    | '/terms'
    | '/collections/$slug'
    | '/admin/activities'
    | '/admin/chats'
    | '/admin/faqs'
    | '/admin/online'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/abandoned-carts'
    | '/admin/categories'
    | '/admin/collections'
    | '/admin/coupons'
    | '/admin/gallery'
    | '/admin/orders'
    | '/admin/reviews'
    | '/api/auth/$'
    | '/collections'
    | '/admin/coupons/analytics'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/checkout'
    | '/offline'
    | '/home'
    | '/bulk'
    | '/cart'
    | '/wishlist'
    | '/admin/shared'
    | '/api/push-event'
    | '/payment/verify'
    | '/'
    | '/admin'
    | '/auth/error'
    | '/auth/signin'
    | '/auth/signup'
    | '/auth/verify-request'
    | '/about'
    | '/careers'
    | '/contact-us'
    | '/help-center'
    | '/privacy'
    | '/returns'
    | '/shipping'
    | '/terms'
    | '/collections/$slug'
    | '/admin/activities'
    | '/admin/chats'
    | '/admin/faqs'
    | '/admin/online'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/abandoned-carts'
    | '/admin/categories'
    | '/admin/collections'
    | '/admin/coupons'
    | '/admin/gallery'
    | '/admin/orders'
    | '/admin/reviews'
    | '/api/auth/$'
    | '/collections'
    | '/admin/coupons/analytics'
  id:
    | '__root__'
    | '/_authLayout'
    | '/_mainLayout'
    | '/admin'
    | '/checkout'
    | '/offline'
    | '/_authLayout/home'
    | '/_mainLayout/bulk'
    | '/_mainLayout/cart'
    | '/_mainLayout/wishlist'
    | '/admin/shared'
    | '/api/push-event'
    | '/payment/verify'
    | '/_mainLayout/'
    | '/admin/'
    | '/_authLayout/auth/error'
    | '/_authLayout/auth/signin'
    | '/_authLayout/auth/signup'
    | '/_authLayout/auth/verify-request'
    | '/_mainLayout/(static)/about'
    | '/_mainLayout/(static)/careers'
    | '/_mainLayout/(static)/contact-us'
    | '/_mainLayout/(static)/help-center'
    | '/_mainLayout/(static)/privacy'
    | '/_mainLayout/(static)/returns'
    | '/_mainLayout/(static)/shipping'
    | '/_mainLayout/(static)/terms'
    | '/_mainLayout/collections/$slug'
    | '/admin/(admin)/activities'
    | '/admin/(admin)/chats'
    | '/admin/(admin)/faqs'
    | '/admin/(admin)/online'
    | '/admin/(admin)/settings'
    | '/admin/(admin)/users'
    | '/admin/(store)/abandoned-carts'
    | '/admin/(store)/categories'
    | '/admin/(store)/collections'
    | '/admin/(store)/coupons'
    | '/admin/(store)/gallery'
    | '/admin/(store)/orders'
    | '/admin/(store)/reviews'
    | '/api/auth/$'
    | '/_mainLayout/collections/'
    | '/admin/(store)/coupons/analytics'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren
  MainLayoutRoute: typeof MainLayoutRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  CheckoutRoute: typeof CheckoutRoute
  OfflineRoute: typeof OfflineRoute
  ApiPushEventRoute: typeof ApiPushEventRoute
  PaymentVerifyRoute: typeof PaymentVerifyRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/offline': {
      id: '/offline'
      path: '/offline'
      fullPath: '/offline'
      preLoaderRoute: typeof OfflineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_mainLayout': {
      id: '/_mainLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof MainLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authLayout': {
      id: '/_authLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_mainLayout/': {
      id: '/_mainLayout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainLayoutIndexRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/payment/verify': {
      id: '/payment/verify'
      path: '/payment/verify'
      fullPath: '/payment/verify'
      preLoaderRoute: typeof PaymentVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/push-event': {
      id: '/api/push-event'
      path: '/api/push-event'
      fullPath: '/api/push-event'
      preLoaderRoute: typeof ApiPushEventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/shared': {
      id: '/admin/shared'
      path: '/shared'
      fullPath: '/admin/shared'
      preLoaderRoute: typeof AdminSharedRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_mainLayout/wishlist': {
      id: '/_mainLayout/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof MainLayoutWishlistRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_mainLayout/cart': {
      id: '/_mainLayout/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof MainLayoutCartRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_mainLayout/bulk': {
      id: '/_mainLayout/bulk'
      path: '/bulk'
      fullPath: '/bulk'
      preLoaderRoute: typeof MainLayoutBulkRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_authLayout/home': {
      id: '/_authLayout/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthLayoutHomeRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_mainLayout/collections/': {
      id: '/_mainLayout/collections/'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof MainLayoutCollectionsIndexRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/(store)/reviews': {
      id: '/admin/(store)/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminstoreReviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/(store)/orders': {
      id: '/admin/(store)/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminstoreOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/(store)/gallery': {
      id: '/admin/(store)/gallery'
      path: '/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AdminstoreGalleryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/(store)/coupons': {
      id: '/admin/(store)/coupons'
      path: '/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AdminstoreCouponsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/(store)/collections': {
      id: '/admin/(store)/collections'
      path: '/collections'
      fullPath: '/admin/collections'
      preLoaderRoute: typeof AdminstoreCollectionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/(store)/categories': {
      id: '/admin/(store)/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminstoreCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/(store)/abandoned-carts': {
      id: '/admin/(store)/abandoned-carts'
      path: '/abandoned-carts'
      fullPath: '/admin/abandoned-carts'
      preLoaderRoute: typeof AdminstoreAbandonedCartsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/(admin)/users': {
      id: '/admin/(admin)/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminadminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/(admin)/settings': {
      id: '/admin/(admin)/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminadminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/(admin)/online': {
      id: '/admin/(admin)/online'
      path: '/online'
      fullPath: '/admin/online'
      preLoaderRoute: typeof AdminadminOnlineRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/(admin)/faqs': {
      id: '/admin/(admin)/faqs'
      path: '/faqs'
      fullPath: '/admin/faqs'
      preLoaderRoute: typeof AdminadminFaqsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/(admin)/chats': {
      id: '/admin/(admin)/chats'
      path: '/chats'
      fullPath: '/admin/chats'
      preLoaderRoute: typeof AdminadminChatsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/(admin)/activities': {
      id: '/admin/(admin)/activities'
      path: '/activities'
      fullPath: '/admin/activities'
      preLoaderRoute: typeof AdminadminActivitiesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_mainLayout/collections/$slug': {
      id: '/_mainLayout/collections/$slug'
      path: '/collections/$slug'
      fullPath: '/collections/$slug'
      preLoaderRoute: typeof MainLayoutCollectionsSlugRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_mainLayout/(static)/terms': {
      id: '/_mainLayout/(static)/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof MainLayoutstaticTermsRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_mainLayout/(static)/shipping': {
      id: '/_mainLayout/(static)/shipping'
      path: '/shipping'
      fullPath: '/shipping'
      preLoaderRoute: typeof MainLayoutstaticShippingRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_mainLayout/(static)/returns': {
      id: '/_mainLayout/(static)/returns'
      path: '/returns'
      fullPath: '/returns'
      preLoaderRoute: typeof MainLayoutstaticReturnsRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_mainLayout/(static)/privacy': {
      id: '/_mainLayout/(static)/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof MainLayoutstaticPrivacyRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_mainLayout/(static)/help-center': {
      id: '/_mainLayout/(static)/help-center'
      path: '/help-center'
      fullPath: '/help-center'
      preLoaderRoute: typeof MainLayoutstaticHelpCenterRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_mainLayout/(static)/contact-us': {
      id: '/_mainLayout/(static)/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof MainLayoutstaticContactUsRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_mainLayout/(static)/careers': {
      id: '/_mainLayout/(static)/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof MainLayoutstaticCareersRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_mainLayout/(static)/about': {
      id: '/_mainLayout/(static)/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof MainLayoutstaticAboutRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_authLayout/auth/verify-request': {
      id: '/_authLayout/auth/verify-request'
      path: '/auth/verify-request'
      fullPath: '/auth/verify-request'
      preLoaderRoute: typeof AuthLayoutAuthVerifyRequestRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_authLayout/auth/signup': {
      id: '/_authLayout/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthLayoutAuthSignupRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_authLayout/auth/signin': {
      id: '/_authLayout/auth/signin'
      path: '/auth/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof AuthLayoutAuthSigninRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_authLayout/auth/error': {
      id: '/_authLayout/auth/error'
      path: '/auth/error'
      fullPath: '/auth/error'
      preLoaderRoute: typeof AuthLayoutAuthErrorRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/admin/(store)/coupons/analytics': {
      id: '/admin/(store)/coupons/analytics'
      path: '/analytics'
      fullPath: '/admin/coupons/analytics'
      preLoaderRoute: typeof AdminstoreCouponsAnalyticsRouteImport
      parentRoute: typeof AdminstoreCouponsRoute
    }
  }
}

interface AuthLayoutRouteChildren {
  AuthLayoutHomeRoute: typeof AuthLayoutHomeRoute
  AuthLayoutAuthErrorRoute: typeof AuthLayoutAuthErrorRoute
  AuthLayoutAuthSigninRoute: typeof AuthLayoutAuthSigninRoute
  AuthLayoutAuthSignupRoute: typeof AuthLayoutAuthSignupRoute
  AuthLayoutAuthVerifyRequestRoute: typeof AuthLayoutAuthVerifyRequestRoute
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthLayoutHomeRoute: AuthLayoutHomeRoute,
  AuthLayoutAuthErrorRoute: AuthLayoutAuthErrorRoute,
  AuthLayoutAuthSigninRoute: AuthLayoutAuthSigninRoute,
  AuthLayoutAuthSignupRoute: AuthLayoutAuthSignupRoute,
  AuthLayoutAuthVerifyRequestRoute: AuthLayoutAuthVerifyRequestRoute,
}

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
)

interface MainLayoutRouteChildren {
  MainLayoutBulkRoute: typeof MainLayoutBulkRoute
  MainLayoutCartRoute: typeof MainLayoutCartRoute
  MainLayoutWishlistRoute: typeof MainLayoutWishlistRoute
  MainLayoutIndexRoute: typeof MainLayoutIndexRoute
  MainLayoutstaticAboutRoute: typeof MainLayoutstaticAboutRoute
  MainLayoutstaticCareersRoute: typeof MainLayoutstaticCareersRoute
  MainLayoutstaticContactUsRoute: typeof MainLayoutstaticContactUsRoute
  MainLayoutstaticHelpCenterRoute: typeof MainLayoutstaticHelpCenterRoute
  MainLayoutstaticPrivacyRoute: typeof MainLayoutstaticPrivacyRoute
  MainLayoutstaticReturnsRoute: typeof MainLayoutstaticReturnsRoute
  MainLayoutstaticShippingRoute: typeof MainLayoutstaticShippingRoute
  MainLayoutstaticTermsRoute: typeof MainLayoutstaticTermsRoute
  MainLayoutCollectionsSlugRoute: typeof MainLayoutCollectionsSlugRoute
  MainLayoutCollectionsIndexRoute: typeof MainLayoutCollectionsIndexRoute
}

const MainLayoutRouteChildren: MainLayoutRouteChildren = {
  MainLayoutBulkRoute: MainLayoutBulkRoute,
  MainLayoutCartRoute: MainLayoutCartRoute,
  MainLayoutWishlistRoute: MainLayoutWishlistRoute,
  MainLayoutIndexRoute: MainLayoutIndexRoute,
  MainLayoutstaticAboutRoute: MainLayoutstaticAboutRoute,
  MainLayoutstaticCareersRoute: MainLayoutstaticCareersRoute,
  MainLayoutstaticContactUsRoute: MainLayoutstaticContactUsRoute,
  MainLayoutstaticHelpCenterRoute: MainLayoutstaticHelpCenterRoute,
  MainLayoutstaticPrivacyRoute: MainLayoutstaticPrivacyRoute,
  MainLayoutstaticReturnsRoute: MainLayoutstaticReturnsRoute,
  MainLayoutstaticShippingRoute: MainLayoutstaticShippingRoute,
  MainLayoutstaticTermsRoute: MainLayoutstaticTermsRoute,
  MainLayoutCollectionsSlugRoute: MainLayoutCollectionsSlugRoute,
  MainLayoutCollectionsIndexRoute: MainLayoutCollectionsIndexRoute,
}

const MainLayoutRouteWithChildren = MainLayoutRoute._addFileChildren(
  MainLayoutRouteChildren,
)

interface AdminstoreCouponsRouteChildren {
  AdminstoreCouponsAnalyticsRoute: typeof AdminstoreCouponsAnalyticsRoute
}

const AdminstoreCouponsRouteChildren: AdminstoreCouponsRouteChildren = {
  AdminstoreCouponsAnalyticsRoute: AdminstoreCouponsAnalyticsRoute,
}

const AdminstoreCouponsRouteWithChildren =
  AdminstoreCouponsRoute._addFileChildren(AdminstoreCouponsRouteChildren)

interface AdminRouteChildren {
  AdminSharedRoute: typeof AdminSharedRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminadminActivitiesRoute: typeof AdminadminActivitiesRoute
  AdminadminChatsRoute: typeof AdminadminChatsRoute
  AdminadminFaqsRoute: typeof AdminadminFaqsRoute
  AdminadminOnlineRoute: typeof AdminadminOnlineRoute
  AdminadminSettingsRoute: typeof AdminadminSettingsRoute
  AdminadminUsersRoute: typeof AdminadminUsersRoute
  AdminstoreAbandonedCartsRoute: typeof AdminstoreAbandonedCartsRoute
  AdminstoreCategoriesRoute: typeof AdminstoreCategoriesRoute
  AdminstoreCollectionsRoute: typeof AdminstoreCollectionsRoute
  AdminstoreCouponsRoute: typeof AdminstoreCouponsRouteWithChildren
  AdminstoreGalleryRoute: typeof AdminstoreGalleryRoute
  AdminstoreOrdersRoute: typeof AdminstoreOrdersRoute
  AdminstoreReviewsRoute: typeof AdminstoreReviewsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminSharedRoute: AdminSharedRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminadminActivitiesRoute: AdminadminActivitiesRoute,
  AdminadminChatsRoute: AdminadminChatsRoute,
  AdminadminFaqsRoute: AdminadminFaqsRoute,
  AdminadminOnlineRoute: AdminadminOnlineRoute,
  AdminadminSettingsRoute: AdminadminSettingsRoute,
  AdminadminUsersRoute: AdminadminUsersRoute,
  AdminstoreAbandonedCartsRoute: AdminstoreAbandonedCartsRoute,
  AdminstoreCategoriesRoute: AdminstoreCategoriesRoute,
  AdminstoreCollectionsRoute: AdminstoreCollectionsRoute,
  AdminstoreCouponsRoute: AdminstoreCouponsRouteWithChildren,
  AdminstoreGalleryRoute: AdminstoreGalleryRoute,
  AdminstoreOrdersRoute: AdminstoreOrdersRoute,
  AdminstoreReviewsRoute: AdminstoreReviewsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
  MainLayoutRoute: MainLayoutRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  CheckoutRoute: CheckoutRoute,
  OfflineRoute: OfflineRoute,
  ApiPushEventRoute: ApiPushEventRoute,
  PaymentVerifyRoute: PaymentVerifyRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
