/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OfflineRouteImport } from './routes/offline'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as MainLayoutRouteImport } from './routes/_mainLayout'
import { Route as AuthLayoutRouteImport } from './routes/_authLayout'
import { Route as AdminLayoutRouteImport } from './routes/_adminLayout'
import { Route as MainLayoutIndexRouteImport } from './routes/_mainLayout/index'
import { Route as PaymentVerifyRouteImport } from './routes/payment.verify'
import { Route as ApiPushEventRouteImport } from './routes/api/push-event'
import { Route as MainLayoutWishlistRouteImport } from './routes/_mainLayout/wishlist'
import { Route as MainLayoutCartRouteImport } from './routes/_mainLayout/cart'
import { Route as MainLayoutBulkRouteImport } from './routes/_mainLayout/bulk'
import { Route as MainLayoutAccountRouteImport } from './routes/_mainLayout/account'
import { Route as MainLayoutCollectionsIndexRouteImport } from './routes/_mainLayout/collections/index'
import { Route as MainLayoutAccountIndexRouteImport } from './routes/_mainLayout/account/index'
import { Route as AdminLayoutAdminIndexRouteImport } from './routes/_adminLayout/admin.index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as MainLayoutSearchQueryRouteImport } from './routes/_mainLayout/search.$query'
import { Route as MainLayoutProductsSlugRouteImport } from './routes/_mainLayout/products.$slug'
import { Route as MainLayoutCollectionsSlugRouteImport } from './routes/_mainLayout/collections/$slug'
import { Route as MainLayoutCatalogSlugRouteImport } from './routes/_mainLayout/catalog.$slug'
import { Route as MainLayoutAccountReferralsRouteImport } from './routes/_mainLayout/account/referrals'
import { Route as MainLayoutAccountProfileRouteImport } from './routes/_mainLayout/account/profile'
import { Route as MainLayoutAccountOrdersRouteImport } from './routes/_mainLayout/account/orders'
import { Route as MainLayoutAccountAddressesRouteImport } from './routes/_mainLayout/account/addresses'
import { Route as MainLayoutstaticTermsRouteImport } from './routes/_mainLayout/(static)/terms'
import { Route as MainLayoutstaticShippingRouteImport } from './routes/_mainLayout/(static)/shipping'
import { Route as MainLayoutstaticReturnsRouteImport } from './routes/_mainLayout/(static)/returns'
import { Route as MainLayoutstaticPrivacyRouteImport } from './routes/_mainLayout/(static)/privacy'
import { Route as MainLayoutstaticHelpCenterRouteImport } from './routes/_mainLayout/(static)/help-center'
import { Route as MainLayoutstaticContactUsRouteImport } from './routes/_mainLayout/(static)/contact-us'
import { Route as MainLayoutstaticCareersRouteImport } from './routes/_mainLayout/(static)/careers'
import { Route as MainLayoutstaticAboutRouteImport } from './routes/_mainLayout/(static)/about'
import { Route as AuthLayoutAuthVerifyRequestRouteImport } from './routes/_authLayout/auth/verify-request'
import { Route as AuthLayoutAuthSignupRouteImport } from './routes/_authLayout/auth/signup'
import { Route as AuthLayoutAuthSigninRouteImport } from './routes/_authLayout/auth/signin'
import { Route as AuthLayoutAuthErrorRouteImport } from './routes/_authLayout/auth/error'
import { Route as AdminLayoutAdminCatalogRouteImport } from './routes/_adminLayout/admin.catalog'
import { Route as MainLayoutOrderConfirmedIdRouteImport } from './routes/_mainLayout/order.confirmed.$id'
import { Route as AdminLayoutAdminstoreReviewsRouteImport } from './routes/_adminLayout/admin/(store)/reviews'
import { Route as AdminLayoutAdminstoreOrdersRouteImport } from './routes/_adminLayout/admin/(store)/orders'
import { Route as AdminLayoutAdminstoreGalleryRouteImport } from './routes/_adminLayout/admin/(store)/gallery'
import { Route as AdminLayoutAdminstoreCouponsRouteImport } from './routes/_adminLayout/admin/(store)/coupons'
import { Route as AdminLayoutAdminstoreCollectionsRouteImport } from './routes/_adminLayout/admin/(store)/collections'
import { Route as AdminLayoutAdminstoreCategoriesRouteImport } from './routes/_adminLayout/admin/(store)/categories'
import { Route as AdminLayoutAdminstoreAbandonedCartsRouteImport } from './routes/_adminLayout/admin/(store)/abandoned-carts'
import { Route as AdminLayoutAdminadminUsersRouteImport } from './routes/_adminLayout/admin/(admin)/users'
import { Route as AdminLayoutAdminadminSettingsRouteImport } from './routes/_adminLayout/admin/(admin)/settings'
import { Route as AdminLayoutAdminadminOnlineRouteImport } from './routes/_adminLayout/admin/(admin)/online'
import { Route as AdminLayoutAdminadminFaqsRouteImport } from './routes/_adminLayout/admin/(admin)/faqs'
import { Route as AdminLayoutAdminadminChatsRouteImport } from './routes/_adminLayout/admin/(admin)/chats'
import { Route as AdminLayoutAdminadminActivitiesRouteImport } from './routes/_adminLayout/admin/(admin)/activities'
import { Route as AdminLayoutAdminstoreCouponsAnalyticsRouteImport } from './routes/_adminLayout/admin/(store)/coupons.analytics'

const OfflineRoute = OfflineRouteImport.update({
  id: '/offline',
  path: '/offline',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const MainLayoutRoute = MainLayoutRouteImport.update({
  id: '/_mainLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: '/_authLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLayoutRoute = AdminLayoutRouteImport.update({
  id: '/_adminLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const MainLayoutIndexRoute = MainLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainLayoutRoute,
} as any)
const PaymentVerifyRoute = PaymentVerifyRouteImport.update({
  id: '/payment/verify',
  path: '/payment/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPushEventRoute = ApiPushEventRouteImport.update({
  id: '/api/push-event',
  path: '/api/push-event',
  getParentRoute: () => rootRouteImport,
} as any)
const MainLayoutWishlistRoute = MainLayoutWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainLayoutCartRoute = MainLayoutCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainLayoutBulkRoute = MainLayoutBulkRouteImport.update({
  id: '/bulk',
  path: '/bulk',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainLayoutAccountRoute = MainLayoutAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainLayoutCollectionsIndexRoute =
  MainLayoutCollectionsIndexRouteImport.update({
    id: '/collections/',
    path: '/collections/',
    getParentRoute: () => MainLayoutRoute,
  } as any)
const MainLayoutAccountIndexRoute = MainLayoutAccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainLayoutAccountRoute,
} as any)
const AdminLayoutAdminIndexRoute = AdminLayoutAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const MainLayoutSearchQueryRoute = MainLayoutSearchQueryRouteImport.update({
  id: '/search/$query',
  path: '/search/$query',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainLayoutProductsSlugRoute = MainLayoutProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainLayoutCollectionsSlugRoute =
  MainLayoutCollectionsSlugRouteImport.update({
    id: '/collections/$slug',
    path: '/collections/$slug',
    getParentRoute: () => MainLayoutRoute,
  } as any)
const MainLayoutCatalogSlugRoute = MainLayoutCatalogSlugRouteImport.update({
  id: '/catalog/$slug',
  path: '/catalog/$slug',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainLayoutAccountReferralsRoute =
  MainLayoutAccountReferralsRouteImport.update({
    id: '/referrals',
    path: '/referrals',
    getParentRoute: () => MainLayoutAccountRoute,
  } as any)
const MainLayoutAccountProfileRoute =
  MainLayoutAccountProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => MainLayoutAccountRoute,
  } as any)
const MainLayoutAccountOrdersRoute = MainLayoutAccountOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => MainLayoutAccountRoute,
} as any)
const MainLayoutAccountAddressesRoute =
  MainLayoutAccountAddressesRouteImport.update({
    id: '/addresses',
    path: '/addresses',
    getParentRoute: () => MainLayoutAccountRoute,
  } as any)
const MainLayoutstaticTermsRoute = MainLayoutstaticTermsRouteImport.update({
  id: '/(static)/terms',
  path: '/terms',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainLayoutstaticShippingRoute =
  MainLayoutstaticShippingRouteImport.update({
    id: '/(static)/shipping',
    path: '/shipping',
    getParentRoute: () => MainLayoutRoute,
  } as any)
const MainLayoutstaticReturnsRoute = MainLayoutstaticReturnsRouteImport.update({
  id: '/(static)/returns',
  path: '/returns',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainLayoutstaticPrivacyRoute = MainLayoutstaticPrivacyRouteImport.update({
  id: '/(static)/privacy',
  path: '/privacy',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainLayoutstaticHelpCenterRoute =
  MainLayoutstaticHelpCenterRouteImport.update({
    id: '/(static)/help-center',
    path: '/help-center',
    getParentRoute: () => MainLayoutRoute,
  } as any)
const MainLayoutstaticContactUsRoute =
  MainLayoutstaticContactUsRouteImport.update({
    id: '/(static)/contact-us',
    path: '/contact-us',
    getParentRoute: () => MainLayoutRoute,
  } as any)
const MainLayoutstaticCareersRoute = MainLayoutstaticCareersRouteImport.update({
  id: '/(static)/careers',
  path: '/careers',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainLayoutstaticAboutRoute = MainLayoutstaticAboutRouteImport.update({
  id: '/(static)/about',
  path: '/about',
  getParentRoute: () => MainLayoutRoute,
} as any)
const AuthLayoutAuthVerifyRequestRoute =
  AuthLayoutAuthVerifyRequestRouteImport.update({
    id: '/auth/verify-request',
    path: '/auth/verify-request',
    getParentRoute: () => AuthLayoutRoute,
  } as any)
const AuthLayoutAuthSignupRoute = AuthLayoutAuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthLayoutAuthSigninRoute = AuthLayoutAuthSigninRouteImport.update({
  id: '/auth/signin',
  path: '/auth/signin',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthLayoutAuthErrorRoute = AuthLayoutAuthErrorRouteImport.update({
  id: '/auth/error',
  path: '/auth/error',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AdminLayoutAdminCatalogRoute = AdminLayoutAdminCatalogRouteImport.update({
  id: '/admin/catalog',
  path: '/admin/catalog',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const MainLayoutOrderConfirmedIdRoute =
  MainLayoutOrderConfirmedIdRouteImport.update({
    id: '/order/confirmed/$id',
    path: '/order/confirmed/$id',
    getParentRoute: () => MainLayoutRoute,
  } as any)
const AdminLayoutAdminstoreReviewsRoute =
  AdminLayoutAdminstoreReviewsRouteImport.update({
    id: '/admin/(store)/reviews',
    path: '/admin/reviews',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const AdminLayoutAdminstoreOrdersRoute =
  AdminLayoutAdminstoreOrdersRouteImport.update({
    id: '/admin/(store)/orders',
    path: '/admin/orders',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const AdminLayoutAdminstoreGalleryRoute =
  AdminLayoutAdminstoreGalleryRouteImport.update({
    id: '/admin/(store)/gallery',
    path: '/admin/gallery',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const AdminLayoutAdminstoreCouponsRoute =
  AdminLayoutAdminstoreCouponsRouteImport.update({
    id: '/admin/(store)/coupons',
    path: '/admin/coupons',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const AdminLayoutAdminstoreCollectionsRoute =
  AdminLayoutAdminstoreCollectionsRouteImport.update({
    id: '/admin/(store)/collections',
    path: '/admin/collections',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const AdminLayoutAdminstoreCategoriesRoute =
  AdminLayoutAdminstoreCategoriesRouteImport.update({
    id: '/admin/(store)/categories',
    path: '/admin/categories',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const AdminLayoutAdminstoreAbandonedCartsRoute =
  AdminLayoutAdminstoreAbandonedCartsRouteImport.update({
    id: '/admin/(store)/abandoned-carts',
    path: '/admin/abandoned-carts',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const AdminLayoutAdminadminUsersRoute =
  AdminLayoutAdminadminUsersRouteImport.update({
    id: '/admin/(admin)/users',
    path: '/admin/users',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const AdminLayoutAdminadminSettingsRoute =
  AdminLayoutAdminadminSettingsRouteImport.update({
    id: '/admin/(admin)/settings',
    path: '/admin/settings',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const AdminLayoutAdminadminOnlineRoute =
  AdminLayoutAdminadminOnlineRouteImport.update({
    id: '/admin/(admin)/online',
    path: '/admin/online',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const AdminLayoutAdminadminFaqsRoute =
  AdminLayoutAdminadminFaqsRouteImport.update({
    id: '/admin/(admin)/faqs',
    path: '/admin/faqs',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const AdminLayoutAdminadminChatsRoute =
  AdminLayoutAdminadminChatsRouteImport.update({
    id: '/admin/(admin)/chats',
    path: '/admin/chats',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const AdminLayoutAdminadminActivitiesRoute =
  AdminLayoutAdminadminActivitiesRouteImport.update({
    id: '/admin/(admin)/activities',
    path: '/admin/activities',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const AdminLayoutAdminstoreCouponsAnalyticsRoute =
  AdminLayoutAdminstoreCouponsAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AdminLayoutAdminstoreCouponsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/checkout': typeof CheckoutRoute
  '/maintenance': typeof MaintenanceRoute
  '/offline': typeof OfflineRoute
  '/account': typeof MainLayoutAccountRouteWithChildren
  '/bulk': typeof MainLayoutBulkRoute
  '/cart': typeof MainLayoutCartRoute
  '/wishlist': typeof MainLayoutWishlistRoute
  '/api/push-event': typeof ApiPushEventRoute
  '/payment/verify': typeof PaymentVerifyRoute
  '/': typeof MainLayoutIndexRoute
  '/admin/catalog': typeof AdminLayoutAdminCatalogRoute
  '/auth/error': typeof AuthLayoutAuthErrorRoute
  '/auth/signin': typeof AuthLayoutAuthSigninRoute
  '/auth/signup': typeof AuthLayoutAuthSignupRoute
  '/auth/verify-request': typeof AuthLayoutAuthVerifyRequestRoute
  '/about': typeof MainLayoutstaticAboutRoute
  '/careers': typeof MainLayoutstaticCareersRoute
  '/contact-us': typeof MainLayoutstaticContactUsRoute
  '/help-center': typeof MainLayoutstaticHelpCenterRoute
  '/privacy': typeof MainLayoutstaticPrivacyRoute
  '/returns': typeof MainLayoutstaticReturnsRoute
  '/shipping': typeof MainLayoutstaticShippingRoute
  '/terms': typeof MainLayoutstaticTermsRoute
  '/account/addresses': typeof MainLayoutAccountAddressesRoute
  '/account/orders': typeof MainLayoutAccountOrdersRoute
  '/account/profile': typeof MainLayoutAccountProfileRoute
  '/account/referrals': typeof MainLayoutAccountReferralsRoute
  '/catalog/$slug': typeof MainLayoutCatalogSlugRoute
  '/collections/$slug': typeof MainLayoutCollectionsSlugRoute
  '/products/$slug': typeof MainLayoutProductsSlugRoute
  '/search/$query': typeof MainLayoutSearchQueryRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin': typeof AdminLayoutAdminIndexRoute
  '/account/': typeof MainLayoutAccountIndexRoute
  '/collections': typeof MainLayoutCollectionsIndexRoute
  '/admin/activities': typeof AdminLayoutAdminadminActivitiesRoute
  '/admin/chats': typeof AdminLayoutAdminadminChatsRoute
  '/admin/faqs': typeof AdminLayoutAdminadminFaqsRoute
  '/admin/online': typeof AdminLayoutAdminadminOnlineRoute
  '/admin/settings': typeof AdminLayoutAdminadminSettingsRoute
  '/admin/users': typeof AdminLayoutAdminadminUsersRoute
  '/admin/abandoned-carts': typeof AdminLayoutAdminstoreAbandonedCartsRoute
  '/admin/categories': typeof AdminLayoutAdminstoreCategoriesRoute
  '/admin/collections': typeof AdminLayoutAdminstoreCollectionsRoute
  '/admin/coupons': typeof AdminLayoutAdminstoreCouponsRouteWithChildren
  '/admin/gallery': typeof AdminLayoutAdminstoreGalleryRoute
  '/admin/orders': typeof AdminLayoutAdminstoreOrdersRoute
  '/admin/reviews': typeof AdminLayoutAdminstoreReviewsRoute
  '/order/confirmed/$id': typeof MainLayoutOrderConfirmedIdRoute
  '/admin/coupons/analytics': typeof AdminLayoutAdminstoreCouponsAnalyticsRoute
}
export interface FileRoutesByTo {
  '/checkout': typeof CheckoutRoute
  '/maintenance': typeof MaintenanceRoute
  '/offline': typeof OfflineRoute
  '/bulk': typeof MainLayoutBulkRoute
  '/cart': typeof MainLayoutCartRoute
  '/wishlist': typeof MainLayoutWishlistRoute
  '/api/push-event': typeof ApiPushEventRoute
  '/payment/verify': typeof PaymentVerifyRoute
  '/': typeof MainLayoutIndexRoute
  '/admin/catalog': typeof AdminLayoutAdminCatalogRoute
  '/auth/error': typeof AuthLayoutAuthErrorRoute
  '/auth/signin': typeof AuthLayoutAuthSigninRoute
  '/auth/signup': typeof AuthLayoutAuthSignupRoute
  '/auth/verify-request': typeof AuthLayoutAuthVerifyRequestRoute
  '/about': typeof MainLayoutstaticAboutRoute
  '/careers': typeof MainLayoutstaticCareersRoute
  '/contact-us': typeof MainLayoutstaticContactUsRoute
  '/help-center': typeof MainLayoutstaticHelpCenterRoute
  '/privacy': typeof MainLayoutstaticPrivacyRoute
  '/returns': typeof MainLayoutstaticReturnsRoute
  '/shipping': typeof MainLayoutstaticShippingRoute
  '/terms': typeof MainLayoutstaticTermsRoute
  '/account/addresses': typeof MainLayoutAccountAddressesRoute
  '/account/orders': typeof MainLayoutAccountOrdersRoute
  '/account/profile': typeof MainLayoutAccountProfileRoute
  '/account/referrals': typeof MainLayoutAccountReferralsRoute
  '/catalog/$slug': typeof MainLayoutCatalogSlugRoute
  '/collections/$slug': typeof MainLayoutCollectionsSlugRoute
  '/products/$slug': typeof MainLayoutProductsSlugRoute
  '/search/$query': typeof MainLayoutSearchQueryRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin': typeof AdminLayoutAdminIndexRoute
  '/account': typeof MainLayoutAccountIndexRoute
  '/collections': typeof MainLayoutCollectionsIndexRoute
  '/admin/activities': typeof AdminLayoutAdminadminActivitiesRoute
  '/admin/chats': typeof AdminLayoutAdminadminChatsRoute
  '/admin/faqs': typeof AdminLayoutAdminadminFaqsRoute
  '/admin/online': typeof AdminLayoutAdminadminOnlineRoute
  '/admin/settings': typeof AdminLayoutAdminadminSettingsRoute
  '/admin/users': typeof AdminLayoutAdminadminUsersRoute
  '/admin/abandoned-carts': typeof AdminLayoutAdminstoreAbandonedCartsRoute
  '/admin/categories': typeof AdminLayoutAdminstoreCategoriesRoute
  '/admin/collections': typeof AdminLayoutAdminstoreCollectionsRoute
  '/admin/coupons': typeof AdminLayoutAdminstoreCouponsRouteWithChildren
  '/admin/gallery': typeof AdminLayoutAdminstoreGalleryRoute
  '/admin/orders': typeof AdminLayoutAdminstoreOrdersRoute
  '/admin/reviews': typeof AdminLayoutAdminstoreReviewsRoute
  '/order/confirmed/$id': typeof MainLayoutOrderConfirmedIdRoute
  '/admin/coupons/analytics': typeof AdminLayoutAdminstoreCouponsAnalyticsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_adminLayout': typeof AdminLayoutRouteWithChildren
  '/_authLayout': typeof AuthLayoutRouteWithChildren
  '/_mainLayout': typeof MainLayoutRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/maintenance': typeof MaintenanceRoute
  '/offline': typeof OfflineRoute
  '/_mainLayout/account': typeof MainLayoutAccountRouteWithChildren
  '/_mainLayout/bulk': typeof MainLayoutBulkRoute
  '/_mainLayout/cart': typeof MainLayoutCartRoute
  '/_mainLayout/wishlist': typeof MainLayoutWishlistRoute
  '/api/push-event': typeof ApiPushEventRoute
  '/payment/verify': typeof PaymentVerifyRoute
  '/_mainLayout/': typeof MainLayoutIndexRoute
  '/_adminLayout/admin/catalog': typeof AdminLayoutAdminCatalogRoute
  '/_authLayout/auth/error': typeof AuthLayoutAuthErrorRoute
  '/_authLayout/auth/signin': typeof AuthLayoutAuthSigninRoute
  '/_authLayout/auth/signup': typeof AuthLayoutAuthSignupRoute
  '/_authLayout/auth/verify-request': typeof AuthLayoutAuthVerifyRequestRoute
  '/_mainLayout/(static)/about': typeof MainLayoutstaticAboutRoute
  '/_mainLayout/(static)/careers': typeof MainLayoutstaticCareersRoute
  '/_mainLayout/(static)/contact-us': typeof MainLayoutstaticContactUsRoute
  '/_mainLayout/(static)/help-center': typeof MainLayoutstaticHelpCenterRoute
  '/_mainLayout/(static)/privacy': typeof MainLayoutstaticPrivacyRoute
  '/_mainLayout/(static)/returns': typeof MainLayoutstaticReturnsRoute
  '/_mainLayout/(static)/shipping': typeof MainLayoutstaticShippingRoute
  '/_mainLayout/(static)/terms': typeof MainLayoutstaticTermsRoute
  '/_mainLayout/account/addresses': typeof MainLayoutAccountAddressesRoute
  '/_mainLayout/account/orders': typeof MainLayoutAccountOrdersRoute
  '/_mainLayout/account/profile': typeof MainLayoutAccountProfileRoute
  '/_mainLayout/account/referrals': typeof MainLayoutAccountReferralsRoute
  '/_mainLayout/catalog/$slug': typeof MainLayoutCatalogSlugRoute
  '/_mainLayout/collections/$slug': typeof MainLayoutCollectionsSlugRoute
  '/_mainLayout/products/$slug': typeof MainLayoutProductsSlugRoute
  '/_mainLayout/search/$query': typeof MainLayoutSearchQueryRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_adminLayout/admin/': typeof AdminLayoutAdminIndexRoute
  '/_mainLayout/account/': typeof MainLayoutAccountIndexRoute
  '/_mainLayout/collections/': typeof MainLayoutCollectionsIndexRoute
  '/_adminLayout/admin/(admin)/activities': typeof AdminLayoutAdminadminActivitiesRoute
  '/_adminLayout/admin/(admin)/chats': typeof AdminLayoutAdminadminChatsRoute
  '/_adminLayout/admin/(admin)/faqs': typeof AdminLayoutAdminadminFaqsRoute
  '/_adminLayout/admin/(admin)/online': typeof AdminLayoutAdminadminOnlineRoute
  '/_adminLayout/admin/(admin)/settings': typeof AdminLayoutAdminadminSettingsRoute
  '/_adminLayout/admin/(admin)/users': typeof AdminLayoutAdminadminUsersRoute
  '/_adminLayout/admin/(store)/abandoned-carts': typeof AdminLayoutAdminstoreAbandonedCartsRoute
  '/_adminLayout/admin/(store)/categories': typeof AdminLayoutAdminstoreCategoriesRoute
  '/_adminLayout/admin/(store)/collections': typeof AdminLayoutAdminstoreCollectionsRoute
  '/_adminLayout/admin/(store)/coupons': typeof AdminLayoutAdminstoreCouponsRouteWithChildren
  '/_adminLayout/admin/(store)/gallery': typeof AdminLayoutAdminstoreGalleryRoute
  '/_adminLayout/admin/(store)/orders': typeof AdminLayoutAdminstoreOrdersRoute
  '/_adminLayout/admin/(store)/reviews': typeof AdminLayoutAdminstoreReviewsRoute
  '/_mainLayout/order/confirmed/$id': typeof MainLayoutOrderConfirmedIdRoute
  '/_adminLayout/admin/(store)/coupons/analytics': typeof AdminLayoutAdminstoreCouponsAnalyticsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/checkout'
    | '/maintenance'
    | '/offline'
    | '/account'
    | '/bulk'
    | '/cart'
    | '/wishlist'
    | '/api/push-event'
    | '/payment/verify'
    | '/'
    | '/admin/catalog'
    | '/auth/error'
    | '/auth/signin'
    | '/auth/signup'
    | '/auth/verify-request'
    | '/about'
    | '/careers'
    | '/contact-us'
    | '/help-center'
    | '/privacy'
    | '/returns'
    | '/shipping'
    | '/terms'
    | '/account/addresses'
    | '/account/orders'
    | '/account/profile'
    | '/account/referrals'
    | '/catalog/$slug'
    | '/collections/$slug'
    | '/products/$slug'
    | '/search/$query'
    | '/api/auth/$'
    | '/admin'
    | '/account/'
    | '/collections'
    | '/admin/activities'
    | '/admin/chats'
    | '/admin/faqs'
    | '/admin/online'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/abandoned-carts'
    | '/admin/categories'
    | '/admin/collections'
    | '/admin/coupons'
    | '/admin/gallery'
    | '/admin/orders'
    | '/admin/reviews'
    | '/order/confirmed/$id'
    | '/admin/coupons/analytics'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/checkout'
    | '/maintenance'
    | '/offline'
    | '/bulk'
    | '/cart'
    | '/wishlist'
    | '/api/push-event'
    | '/payment/verify'
    | '/'
    | '/admin/catalog'
    | '/auth/error'
    | '/auth/signin'
    | '/auth/signup'
    | '/auth/verify-request'
    | '/about'
    | '/careers'
    | '/contact-us'
    | '/help-center'
    | '/privacy'
    | '/returns'
    | '/shipping'
    | '/terms'
    | '/account/addresses'
    | '/account/orders'
    | '/account/profile'
    | '/account/referrals'
    | '/catalog/$slug'
    | '/collections/$slug'
    | '/products/$slug'
    | '/search/$query'
    | '/api/auth/$'
    | '/admin'
    | '/account'
    | '/collections'
    | '/admin/activities'
    | '/admin/chats'
    | '/admin/faqs'
    | '/admin/online'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/abandoned-carts'
    | '/admin/categories'
    | '/admin/collections'
    | '/admin/coupons'
    | '/admin/gallery'
    | '/admin/orders'
    | '/admin/reviews'
    | '/order/confirmed/$id'
    | '/admin/coupons/analytics'
  id:
    | '__root__'
    | '/_adminLayout'
    | '/_authLayout'
    | '/_mainLayout'
    | '/checkout'
    | '/maintenance'
    | '/offline'
    | '/_mainLayout/account'
    | '/_mainLayout/bulk'
    | '/_mainLayout/cart'
    | '/_mainLayout/wishlist'
    | '/api/push-event'
    | '/payment/verify'
    | '/_mainLayout/'
    | '/_adminLayout/admin/catalog'
    | '/_authLayout/auth/error'
    | '/_authLayout/auth/signin'
    | '/_authLayout/auth/signup'
    | '/_authLayout/auth/verify-request'
    | '/_mainLayout/(static)/about'
    | '/_mainLayout/(static)/careers'
    | '/_mainLayout/(static)/contact-us'
    | '/_mainLayout/(static)/help-center'
    | '/_mainLayout/(static)/privacy'
    | '/_mainLayout/(static)/returns'
    | '/_mainLayout/(static)/shipping'
    | '/_mainLayout/(static)/terms'
    | '/_mainLayout/account/addresses'
    | '/_mainLayout/account/orders'
    | '/_mainLayout/account/profile'
    | '/_mainLayout/account/referrals'
    | '/_mainLayout/catalog/$slug'
    | '/_mainLayout/collections/$slug'
    | '/_mainLayout/products/$slug'
    | '/_mainLayout/search/$query'
    | '/api/auth/$'
    | '/_adminLayout/admin/'
    | '/_mainLayout/account/'
    | '/_mainLayout/collections/'
    | '/_adminLayout/admin/(admin)/activities'
    | '/_adminLayout/admin/(admin)/chats'
    | '/_adminLayout/admin/(admin)/faqs'
    | '/_adminLayout/admin/(admin)/online'
    | '/_adminLayout/admin/(admin)/settings'
    | '/_adminLayout/admin/(admin)/users'
    | '/_adminLayout/admin/(store)/abandoned-carts'
    | '/_adminLayout/admin/(store)/categories'
    | '/_adminLayout/admin/(store)/collections'
    | '/_adminLayout/admin/(store)/coupons'
    | '/_adminLayout/admin/(store)/gallery'
    | '/_adminLayout/admin/(store)/orders'
    | '/_adminLayout/admin/(store)/reviews'
    | '/_mainLayout/order/confirmed/$id'
    | '/_adminLayout/admin/(store)/coupons/analytics'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminLayoutRoute: typeof AdminLayoutRouteWithChildren
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren
  MainLayoutRoute: typeof MainLayoutRouteWithChildren
  CheckoutRoute: typeof CheckoutRoute
  MaintenanceRoute: typeof MaintenanceRoute
  OfflineRoute: typeof OfflineRoute
  ApiPushEventRoute: typeof ApiPushEventRoute
  PaymentVerifyRoute: typeof PaymentVerifyRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/offline': {
      id: '/offline'
      path: '/offline'
      fullPath: '/offline'
      preLoaderRoute: typeof OfflineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_mainLayout': {
      id: '/_mainLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof MainLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authLayout': {
      id: '/_authLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_adminLayout': {
      id: '/_adminLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AdminLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_mainLayout/': {
      id: '/_mainLayout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainLayoutIndexRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/payment/verify': {
      id: '/payment/verify'
      path: '/payment/verify'
      fullPath: '/payment/verify'
      preLoaderRoute: typeof PaymentVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/push-event': {
      id: '/api/push-event'
      path: '/api/push-event'
      fullPath: '/api/push-event'
      preLoaderRoute: typeof ApiPushEventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_mainLayout/wishlist': {
      id: '/_mainLayout/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof MainLayoutWishlistRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_mainLayout/cart': {
      id: '/_mainLayout/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof MainLayoutCartRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_mainLayout/bulk': {
      id: '/_mainLayout/bulk'
      path: '/bulk'
      fullPath: '/bulk'
      preLoaderRoute: typeof MainLayoutBulkRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_mainLayout/account': {
      id: '/_mainLayout/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof MainLayoutAccountRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_mainLayout/collections/': {
      id: '/_mainLayout/collections/'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof MainLayoutCollectionsIndexRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_mainLayout/account/': {
      id: '/_mainLayout/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof MainLayoutAccountIndexRouteImport
      parentRoute: typeof MainLayoutAccountRoute
    }
    '/_adminLayout/admin/': {
      id: '/_adminLayout/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminLayoutAdminIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_mainLayout/search/$query': {
      id: '/_mainLayout/search/$query'
      path: '/search/$query'
      fullPath: '/search/$query'
      preLoaderRoute: typeof MainLayoutSearchQueryRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_mainLayout/products/$slug': {
      id: '/_mainLayout/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof MainLayoutProductsSlugRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_mainLayout/collections/$slug': {
      id: '/_mainLayout/collections/$slug'
      path: '/collections/$slug'
      fullPath: '/collections/$slug'
      preLoaderRoute: typeof MainLayoutCollectionsSlugRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_mainLayout/catalog/$slug': {
      id: '/_mainLayout/catalog/$slug'
      path: '/catalog/$slug'
      fullPath: '/catalog/$slug'
      preLoaderRoute: typeof MainLayoutCatalogSlugRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_mainLayout/account/referrals': {
      id: '/_mainLayout/account/referrals'
      path: '/referrals'
      fullPath: '/account/referrals'
      preLoaderRoute: typeof MainLayoutAccountReferralsRouteImport
      parentRoute: typeof MainLayoutAccountRoute
    }
    '/_mainLayout/account/profile': {
      id: '/_mainLayout/account/profile'
      path: '/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof MainLayoutAccountProfileRouteImport
      parentRoute: typeof MainLayoutAccountRoute
    }
    '/_mainLayout/account/orders': {
      id: '/_mainLayout/account/orders'
      path: '/orders'
      fullPath: '/account/orders'
      preLoaderRoute: typeof MainLayoutAccountOrdersRouteImport
      parentRoute: typeof MainLayoutAccountRoute
    }
    '/_mainLayout/account/addresses': {
      id: '/_mainLayout/account/addresses'
      path: '/addresses'
      fullPath: '/account/addresses'
      preLoaderRoute: typeof MainLayoutAccountAddressesRouteImport
      parentRoute: typeof MainLayoutAccountRoute
    }
    '/_mainLayout/(static)/terms': {
      id: '/_mainLayout/(static)/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof MainLayoutstaticTermsRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_mainLayout/(static)/shipping': {
      id: '/_mainLayout/(static)/shipping'
      path: '/shipping'
      fullPath: '/shipping'
      preLoaderRoute: typeof MainLayoutstaticShippingRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_mainLayout/(static)/returns': {
      id: '/_mainLayout/(static)/returns'
      path: '/returns'
      fullPath: '/returns'
      preLoaderRoute: typeof MainLayoutstaticReturnsRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_mainLayout/(static)/privacy': {
      id: '/_mainLayout/(static)/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof MainLayoutstaticPrivacyRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_mainLayout/(static)/help-center': {
      id: '/_mainLayout/(static)/help-center'
      path: '/help-center'
      fullPath: '/help-center'
      preLoaderRoute: typeof MainLayoutstaticHelpCenterRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_mainLayout/(static)/contact-us': {
      id: '/_mainLayout/(static)/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof MainLayoutstaticContactUsRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_mainLayout/(static)/careers': {
      id: '/_mainLayout/(static)/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof MainLayoutstaticCareersRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_mainLayout/(static)/about': {
      id: '/_mainLayout/(static)/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof MainLayoutstaticAboutRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_authLayout/auth/verify-request': {
      id: '/_authLayout/auth/verify-request'
      path: '/auth/verify-request'
      fullPath: '/auth/verify-request'
      preLoaderRoute: typeof AuthLayoutAuthVerifyRequestRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_authLayout/auth/signup': {
      id: '/_authLayout/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthLayoutAuthSignupRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_authLayout/auth/signin': {
      id: '/_authLayout/auth/signin'
      path: '/auth/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof AuthLayoutAuthSigninRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_authLayout/auth/error': {
      id: '/_authLayout/auth/error'
      path: '/auth/error'
      fullPath: '/auth/error'
      preLoaderRoute: typeof AuthLayoutAuthErrorRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_adminLayout/admin/catalog': {
      id: '/_adminLayout/admin/catalog'
      path: '/admin/catalog'
      fullPath: '/admin/catalog'
      preLoaderRoute: typeof AdminLayoutAdminCatalogRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/_mainLayout/order/confirmed/$id': {
      id: '/_mainLayout/order/confirmed/$id'
      path: '/order/confirmed/$id'
      fullPath: '/order/confirmed/$id'
      preLoaderRoute: typeof MainLayoutOrderConfirmedIdRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_adminLayout/admin/(store)/reviews': {
      id: '/_adminLayout/admin/(store)/reviews'
      path: '/admin/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminLayoutAdminstoreReviewsRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/_adminLayout/admin/(store)/orders': {
      id: '/_adminLayout/admin/(store)/orders'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminLayoutAdminstoreOrdersRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/_adminLayout/admin/(store)/gallery': {
      id: '/_adminLayout/admin/(store)/gallery'
      path: '/admin/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AdminLayoutAdminstoreGalleryRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/_adminLayout/admin/(store)/coupons': {
      id: '/_adminLayout/admin/(store)/coupons'
      path: '/admin/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AdminLayoutAdminstoreCouponsRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/_adminLayout/admin/(store)/collections': {
      id: '/_adminLayout/admin/(store)/collections'
      path: '/admin/collections'
      fullPath: '/admin/collections'
      preLoaderRoute: typeof AdminLayoutAdminstoreCollectionsRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/_adminLayout/admin/(store)/categories': {
      id: '/_adminLayout/admin/(store)/categories'
      path: '/admin/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminLayoutAdminstoreCategoriesRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/_adminLayout/admin/(store)/abandoned-carts': {
      id: '/_adminLayout/admin/(store)/abandoned-carts'
      path: '/admin/abandoned-carts'
      fullPath: '/admin/abandoned-carts'
      preLoaderRoute: typeof AdminLayoutAdminstoreAbandonedCartsRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/_adminLayout/admin/(admin)/users': {
      id: '/_adminLayout/admin/(admin)/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminLayoutAdminadminUsersRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/_adminLayout/admin/(admin)/settings': {
      id: '/_adminLayout/admin/(admin)/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminLayoutAdminadminSettingsRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/_adminLayout/admin/(admin)/online': {
      id: '/_adminLayout/admin/(admin)/online'
      path: '/admin/online'
      fullPath: '/admin/online'
      preLoaderRoute: typeof AdminLayoutAdminadminOnlineRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/_adminLayout/admin/(admin)/faqs': {
      id: '/_adminLayout/admin/(admin)/faqs'
      path: '/admin/faqs'
      fullPath: '/admin/faqs'
      preLoaderRoute: typeof AdminLayoutAdminadminFaqsRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/_adminLayout/admin/(admin)/chats': {
      id: '/_adminLayout/admin/(admin)/chats'
      path: '/admin/chats'
      fullPath: '/admin/chats'
      preLoaderRoute: typeof AdminLayoutAdminadminChatsRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/_adminLayout/admin/(admin)/activities': {
      id: '/_adminLayout/admin/(admin)/activities'
      path: '/admin/activities'
      fullPath: '/admin/activities'
      preLoaderRoute: typeof AdminLayoutAdminadminActivitiesRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/_adminLayout/admin/(store)/coupons/analytics': {
      id: '/_adminLayout/admin/(store)/coupons/analytics'
      path: '/analytics'
      fullPath: '/admin/coupons/analytics'
      preLoaderRoute: typeof AdminLayoutAdminstoreCouponsAnalyticsRouteImport
      parentRoute: typeof AdminLayoutAdminstoreCouponsRoute
    }
  }
}

interface AdminLayoutAdminstoreCouponsRouteChildren {
  AdminLayoutAdminstoreCouponsAnalyticsRoute: typeof AdminLayoutAdminstoreCouponsAnalyticsRoute
}

const AdminLayoutAdminstoreCouponsRouteChildren: AdminLayoutAdminstoreCouponsRouteChildren =
  {
    AdminLayoutAdminstoreCouponsAnalyticsRoute:
      AdminLayoutAdminstoreCouponsAnalyticsRoute,
  }

const AdminLayoutAdminstoreCouponsRouteWithChildren =
  AdminLayoutAdminstoreCouponsRoute._addFileChildren(
    AdminLayoutAdminstoreCouponsRouteChildren,
  )

interface AdminLayoutRouteChildren {
  AdminLayoutAdminCatalogRoute: typeof AdminLayoutAdminCatalogRoute
  AdminLayoutAdminIndexRoute: typeof AdminLayoutAdminIndexRoute
  AdminLayoutAdminadminActivitiesRoute: typeof AdminLayoutAdminadminActivitiesRoute
  AdminLayoutAdminadminChatsRoute: typeof AdminLayoutAdminadminChatsRoute
  AdminLayoutAdminadminFaqsRoute: typeof AdminLayoutAdminadminFaqsRoute
  AdminLayoutAdminadminOnlineRoute: typeof AdminLayoutAdminadminOnlineRoute
  AdminLayoutAdminadminSettingsRoute: typeof AdminLayoutAdminadminSettingsRoute
  AdminLayoutAdminadminUsersRoute: typeof AdminLayoutAdminadminUsersRoute
  AdminLayoutAdminstoreAbandonedCartsRoute: typeof AdminLayoutAdminstoreAbandonedCartsRoute
  AdminLayoutAdminstoreCategoriesRoute: typeof AdminLayoutAdminstoreCategoriesRoute
  AdminLayoutAdminstoreCollectionsRoute: typeof AdminLayoutAdminstoreCollectionsRoute
  AdminLayoutAdminstoreCouponsRoute: typeof AdminLayoutAdminstoreCouponsRouteWithChildren
  AdminLayoutAdminstoreGalleryRoute: typeof AdminLayoutAdminstoreGalleryRoute
  AdminLayoutAdminstoreOrdersRoute: typeof AdminLayoutAdminstoreOrdersRoute
  AdminLayoutAdminstoreReviewsRoute: typeof AdminLayoutAdminstoreReviewsRoute
}

const AdminLayoutRouteChildren: AdminLayoutRouteChildren = {
  AdminLayoutAdminCatalogRoute: AdminLayoutAdminCatalogRoute,
  AdminLayoutAdminIndexRoute: AdminLayoutAdminIndexRoute,
  AdminLayoutAdminadminActivitiesRoute: AdminLayoutAdminadminActivitiesRoute,
  AdminLayoutAdminadminChatsRoute: AdminLayoutAdminadminChatsRoute,
  AdminLayoutAdminadminFaqsRoute: AdminLayoutAdminadminFaqsRoute,
  AdminLayoutAdminadminOnlineRoute: AdminLayoutAdminadminOnlineRoute,
  AdminLayoutAdminadminSettingsRoute: AdminLayoutAdminadminSettingsRoute,
  AdminLayoutAdminadminUsersRoute: AdminLayoutAdminadminUsersRoute,
  AdminLayoutAdminstoreAbandonedCartsRoute:
    AdminLayoutAdminstoreAbandonedCartsRoute,
  AdminLayoutAdminstoreCategoriesRoute: AdminLayoutAdminstoreCategoriesRoute,
  AdminLayoutAdminstoreCollectionsRoute: AdminLayoutAdminstoreCollectionsRoute,
  AdminLayoutAdminstoreCouponsRoute:
    AdminLayoutAdminstoreCouponsRouteWithChildren,
  AdminLayoutAdminstoreGalleryRoute: AdminLayoutAdminstoreGalleryRoute,
  AdminLayoutAdminstoreOrdersRoute: AdminLayoutAdminstoreOrdersRoute,
  AdminLayoutAdminstoreReviewsRoute: AdminLayoutAdminstoreReviewsRoute,
}

const AdminLayoutRouteWithChildren = AdminLayoutRoute._addFileChildren(
  AdminLayoutRouteChildren,
)

interface AuthLayoutRouteChildren {
  AuthLayoutAuthErrorRoute: typeof AuthLayoutAuthErrorRoute
  AuthLayoutAuthSigninRoute: typeof AuthLayoutAuthSigninRoute
  AuthLayoutAuthSignupRoute: typeof AuthLayoutAuthSignupRoute
  AuthLayoutAuthVerifyRequestRoute: typeof AuthLayoutAuthVerifyRequestRoute
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthLayoutAuthErrorRoute: AuthLayoutAuthErrorRoute,
  AuthLayoutAuthSigninRoute: AuthLayoutAuthSigninRoute,
  AuthLayoutAuthSignupRoute: AuthLayoutAuthSignupRoute,
  AuthLayoutAuthVerifyRequestRoute: AuthLayoutAuthVerifyRequestRoute,
}

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
)

interface MainLayoutAccountRouteChildren {
  MainLayoutAccountAddressesRoute: typeof MainLayoutAccountAddressesRoute
  MainLayoutAccountOrdersRoute: typeof MainLayoutAccountOrdersRoute
  MainLayoutAccountProfileRoute: typeof MainLayoutAccountProfileRoute
  MainLayoutAccountReferralsRoute: typeof MainLayoutAccountReferralsRoute
  MainLayoutAccountIndexRoute: typeof MainLayoutAccountIndexRoute
}

const MainLayoutAccountRouteChildren: MainLayoutAccountRouteChildren = {
  MainLayoutAccountAddressesRoute: MainLayoutAccountAddressesRoute,
  MainLayoutAccountOrdersRoute: MainLayoutAccountOrdersRoute,
  MainLayoutAccountProfileRoute: MainLayoutAccountProfileRoute,
  MainLayoutAccountReferralsRoute: MainLayoutAccountReferralsRoute,
  MainLayoutAccountIndexRoute: MainLayoutAccountIndexRoute,
}

const MainLayoutAccountRouteWithChildren =
  MainLayoutAccountRoute._addFileChildren(MainLayoutAccountRouteChildren)

interface MainLayoutRouteChildren {
  MainLayoutAccountRoute: typeof MainLayoutAccountRouteWithChildren
  MainLayoutBulkRoute: typeof MainLayoutBulkRoute
  MainLayoutCartRoute: typeof MainLayoutCartRoute
  MainLayoutWishlistRoute: typeof MainLayoutWishlistRoute
  MainLayoutIndexRoute: typeof MainLayoutIndexRoute
  MainLayoutstaticAboutRoute: typeof MainLayoutstaticAboutRoute
  MainLayoutstaticCareersRoute: typeof MainLayoutstaticCareersRoute
  MainLayoutstaticContactUsRoute: typeof MainLayoutstaticContactUsRoute
  MainLayoutstaticHelpCenterRoute: typeof MainLayoutstaticHelpCenterRoute
  MainLayoutstaticPrivacyRoute: typeof MainLayoutstaticPrivacyRoute
  MainLayoutstaticReturnsRoute: typeof MainLayoutstaticReturnsRoute
  MainLayoutstaticShippingRoute: typeof MainLayoutstaticShippingRoute
  MainLayoutstaticTermsRoute: typeof MainLayoutstaticTermsRoute
  MainLayoutCatalogSlugRoute: typeof MainLayoutCatalogSlugRoute
  MainLayoutCollectionsSlugRoute: typeof MainLayoutCollectionsSlugRoute
  MainLayoutProductsSlugRoute: typeof MainLayoutProductsSlugRoute
  MainLayoutSearchQueryRoute: typeof MainLayoutSearchQueryRoute
  MainLayoutCollectionsIndexRoute: typeof MainLayoutCollectionsIndexRoute
  MainLayoutOrderConfirmedIdRoute: typeof MainLayoutOrderConfirmedIdRoute
}

const MainLayoutRouteChildren: MainLayoutRouteChildren = {
  MainLayoutAccountRoute: MainLayoutAccountRouteWithChildren,
  MainLayoutBulkRoute: MainLayoutBulkRoute,
  MainLayoutCartRoute: MainLayoutCartRoute,
  MainLayoutWishlistRoute: MainLayoutWishlistRoute,
  MainLayoutIndexRoute: MainLayoutIndexRoute,
  MainLayoutstaticAboutRoute: MainLayoutstaticAboutRoute,
  MainLayoutstaticCareersRoute: MainLayoutstaticCareersRoute,
  MainLayoutstaticContactUsRoute: MainLayoutstaticContactUsRoute,
  MainLayoutstaticHelpCenterRoute: MainLayoutstaticHelpCenterRoute,
  MainLayoutstaticPrivacyRoute: MainLayoutstaticPrivacyRoute,
  MainLayoutstaticReturnsRoute: MainLayoutstaticReturnsRoute,
  MainLayoutstaticShippingRoute: MainLayoutstaticShippingRoute,
  MainLayoutstaticTermsRoute: MainLayoutstaticTermsRoute,
  MainLayoutCatalogSlugRoute: MainLayoutCatalogSlugRoute,
  MainLayoutCollectionsSlugRoute: MainLayoutCollectionsSlugRoute,
  MainLayoutProductsSlugRoute: MainLayoutProductsSlugRoute,
  MainLayoutSearchQueryRoute: MainLayoutSearchQueryRoute,
  MainLayoutCollectionsIndexRoute: MainLayoutCollectionsIndexRoute,
  MainLayoutOrderConfirmedIdRoute: MainLayoutOrderConfirmedIdRoute,
}

const MainLayoutRouteWithChildren = MainLayoutRoute._addFileChildren(
  MainLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AdminLayoutRoute: AdminLayoutRouteWithChildren,
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
  MainLayoutRoute: MainLayoutRouteWithChildren,
  CheckoutRoute: CheckoutRoute,
  MaintenanceRoute: MaintenanceRoute,
  OfflineRoute: OfflineRoute,
  ApiPushEventRoute: ApiPushEventRoute,
  PaymentVerifyRoute: PaymentVerifyRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
