FROM beafdocker/fastapi-base:latest

ENV FASTEMBED_CACHE_PATH=/app/models

WORKDIR /app

COPY pyproject.toml uv.lock* ./

# Fast container caching layer sync
RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync --frozen --no-install-project

RUN uv run python -c "from fastembed import TextEmbedding; TextEmbedding('sentence-transformers/all-MiniLM-L6-v2', cache_dir='/app/models')"

EXPOSE 8000
CMD ["uv", "run", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
