name: "Labeler"

on:
    workflow_dispatch:

jobs:
    triage:
        permissions:
            contents: read
            pull-requests: write
        runs-on: ubuntu-latest
        steps:
        -   name: Apply labels using labeler
            uses: actions/labeler@v6